file "$(TOP)/db/devAOCRIO.db.template"
{
pattern
{BL, EQ, DTYP, PIN}
{"SOL", "CRIO1:9263A:AO0", "CrioAO", "Mod5/AO0"}
{"SOL", "CRIO1:9263A:AO1", "CrioAO", "Mod5/AO1"}
{"SOL", "CRIO1:9263A:AO2", "CrioAO", "Mod5/AO2"}
{"SOL", "CRIO1:9263A:AO3", "CrioAO", "Mod5/AO3"}
{"SOL", "CRIO1:RT:AO1",    "CrioAO", "RT_DBL_AO1"}
{"SOL", "CRIO1:RT:AO2",    "CrioAO", "RT_SGL_AO2"}
{"SOL", "CRIO1:RT:AO3",    "CrioAO", "RT_I64_AO3"}
{"SOL", "CRIO1:RT:AO4",    "CrioAO", "RT_I32_AO4"}
{"SOL", "CRIO1:RT:AO5",    "CrioAO", "RT_I16_AO5"}
{"SOL", "CRIO1:RT:AO6",    "CrioAO", "RT_I08_AO6"}
{"SOL", "CRIO1:RT:AO7",    "CrioAO", "RT_U64_AO7"}
{"SOL", "CRIO1:RT:AO8",    "CrioAO", "RT_U32_AO8"}
{"SOL", "CRIO1:RT:AO9",    "CrioAO", "RT_U16_AO9"}
{"SOL", "CRIO1:RT:AO10",   "CrioAO", "RT_U08_AO10"}

}















