file "$(TOP)/db/devBICRIO.db.template"
{
pattern
{BL, EQ, DTYP, PIN}
{"SOL", "CRIO1:9403A:BI0",  "CrioBI", "Mod3/DI0"}
{"SOL", "CRIO1:9403A:BI1",  "CrioBI", "Mod3/DI1"}
{"SOL", "CRIO1:9403A:BI2",  "CrioBI", "Mod3/DI2"}
{"SOL", "CRIO1:RT:BI0",     "CrioBI", "RT_BOL_BI0"}
{"SOL", "CRIO1:9403A:BI3",  "CrioBI", "Mod3/DI3"}
{"SOL", "CRIO1:9403A:BI4",  "CrioBI", "Mod3/DI4"}
{"SOL", "CRIO1:9403A:BI5",  "CrioBI", "Mod3/DI5"}
{"SOL", "CRIO1:9403A:BI6",  "CrioBI", "Mod3/DI6"}
{"SOL", "CRIO1:9403A:BI7",  "CrioBI", "Mod3/DI7"}
{"SOL", "CRIO1:9403A:BI8",  "CrioBI", "Mod3/DI8"}
{"SOL", "CRIO1:9403A:BI9",  "CrioBI", "Mod3/DI9"}
{"SOL", "CRIO1:9403A:BI10", "CrioBI", "Mod3/DI10"}
{"SOL", "CRIO1:9403A:BI11", "CrioBI", "Mod3/DI11"}
{"SOL", "CRIO1:9403A:BI12", "CrioBI", "Mod3/DI12"}
{"SOL", "CRIO1:9403A:BI13", "CrioBI", "Mod3/DI13"}
{"SOL", "CRIO1:9403A:BI13", "CrioBI", "Mod3/DI13"}
{"SOL", "CRIO1:9403A:BI14", "CrioBI", "Mod3/DI14"}
{"SOL", "CRIO1:9403A:BI15", "CrioBI", "Mod3/DI15"}
{"SOL", "CRIO1:9401A:BI4",  "CrioBI", "Mod1/DI4"}
{"SOL", "CRIO1:9401A:BI5",  "CrioBI", "Mod1/DI5"}
{"SOL", "CRIO1:9401A:BI6",  "CrioBI", "Mod1/DI6"}
{"SOL", "CRIO1:9401A:BI7",  "CrioBI", "Mod1/DI7"}
{"SOL", "CRIO1:9401B:BI4",  "CrioBI", "Mod2/DI4"}
{"SOL", "CRIO1:9401B:BI5",  "CrioBI", "Mod2/DI5"}
{"SOL", "CRIO1:9401B:BI6",  "CrioBI", "Mod2/DI6"}
{"SOL", "CRIO1:9401B:BI7",  "CrioBI", "Mod2/DI7"}
}
