file "$(TOP)/db/devWAVEFORMCRIO.db.template"
{
pattern
{BL, EQ, DTYP, PIN, FTVL, NELM, DESC}
{"SOL", "CRIO2:WFI08", "CrioWAVEFORM", "WAVEFORM_I8",  "CHAR",   "3", "This is a description for WAVEFORM_I8"}
{"SOL", "CRIO2:WFI16", "CrioWAVEFORM", "WAVEFORM_I16", "SHORT",  "3", "This is a description for WAVEFORM_I16"}
{"SOL", "CRIO2:WFI32", "CrioWAVEFORM", "WAVEFORM_I32", "LONG",   "3", "This is a description for WAVEFORM_I32"}
{"SOL", "CRIO2:WFI64", "CrioWAVEFORM", "WAVEFORM_I64", "DOUBLE", "3", "This is a description for WAVEFORM_I64"}

{"SOL", "CRIO2:WFU08", "CrioWAVEFORM", "WAVEFORM_U8",  "UCHAR",  "3", "This is a description for WAVEFORM_U8"}
{"SOL", "CRIO2:WFU16", "CrioWAVEFORM", "WAVEFORM_U16", "USHORT", "3", "This is a description for WAVEFORM_U16"}
{"SOL", "CRIO2:WFU32", "CrioWAVEFORM", "WAVEFORM_U32", "ULONG",  "3", "This is a description for WAVEFORM_U32"}
{"SOL", "CRIO2:WFU64", "CrioWAVEFORM", "WAVEFORM_U64", "DOUBLE", "3", "This is a description for WAVEFORM_U64"}

{"SOL", "CRIO2:WFSGL", "CrioWAVEFORM", "WAVEFORM_SGL", "FLOAT", "3", "This is a description for WAVEFORM_SGL"}

{"SOL", "CRIO2:RTWF0", "CrioWAVEFORM", "RT_WF0", "FLOAT", "5", "This is a description for RT_WF0"}
{"SOL", "CRIO2:RTWF1", "CrioWAVEFORM", "RT_WF1", "ULONG", "113", "This is a description for RT_WF1"}
{"SOL", "CRIO2:RTWF2", "CrioWAVEFORM", "RT_WF2", "DOUBLE", "4", "This is a description for RT_WF2"}
{"SOL", "CRIO2:RTWF3", "CrioWAVEFORM", "RT_WF3", "LONG", "10", "This is a description for RT_WF3"}
{"SOL", "CRIO2:RTWF4", "CrioWAVEFORM", "RT_WF4", "SHORT", "4", "This is a description for RT_WF4"}
{"SOL", "CRIO2:RTWF5", "CrioWAVEFORM", "RT_WF5", "CHAR", "8", "This is a description for RT_WF5"}
{"SOL", "CRIO2:RTWF6", "CrioWAVEFORM", "RT_WF6", "CHAR", "6", "This is a description for RT_WF6"}
{"SOL", "CRIO2:RTWF7", "CrioWAVEFORM", "RT_WF7", "DOUBLE", "9", "This is a description for RT_WF7"}
{"SOL", "CRIO2:RTWF8", "CrioWAVEFORM", "RT_WF8", "USHORT", "11", "This is a description for RT_WF8"}
{"SOL", "CRIO2:RTWF9", "CrioWAVEFORM", "RT_WF9", "DOUBLE", "5", "This is a description for RT_WF9"}
{"SOL", "CRIO2:RTWF10", "CrioWAVEFORM", "RT_WF10", "UCHAR", "9", "This is a description for RT_WF10"}
}



